#!/usr/bin/env python3
"""Regenerate ``acdoca_generator/config/_field_descriptions_generated.py`` from
``ACDOCA-table-structure.xlsx``.

Reads sheet ``ACDOCA_Fields``, columns ``FIELDNAME`` and ``DESCRIPTION``, and
writes a single ``FIELD_DESCRIPTIONS: dict[str, str]`` mapping (SAP technical
name → short description). Lookup at runtime falls back to ``""`` for any
field absent from the XLSX.

Uses stdlib ``zipfile`` + ``xml.etree.ElementTree`` only — no openpyxl.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import Dict


_REPO = Path(__file__).resolve().parent.parent
_XLSX = _REPO / "ACDOCA-table-structure.xlsx"
_OUT = _REPO / "acdoca_generator" / "config" / "_field_descriptions_generated.py"
_NS = {"a": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}


def _shared_strings(z: zipfile.ZipFile) -> list[str]:
    """Return the shared-strings table indexed by sst id."""
    root = ET.fromstring(z.read("xl/sharedStrings.xml").decode())
    out: list[str] = []
    for si in root.findall("a:si", _NS):
        # <si> may contain a single <t> or multiple rich-text <r><t> runs
        t = si.find("a:t", _NS)
        if t is not None and t.text is not None:
            out.append(t.text)
        else:
            out.append("".join(t.text or "" for t in si.iter() if t.tag.endswith("}t")))
    return out


def _cell_value(cell: ET.Element, strs: list[str]) -> str:
    t = cell.get("t")
    v = cell.find("a:v", _NS)
    if v is None or v.text is None:
        return ""
    if t == "s":
        return strs[int(v.text)]
    if t == "inlineStr":
        inline = cell.find("a:is/a:t", _NS)
        return inline.text if inline is not None and inline.text else ""
    return v.text


def _find_sheet_path(z: zipfile.ZipFile, sheet_name: str) -> str:
    """Resolve sheet name → xl/worksheets/sheetN.xml via the workbook+rels."""
    wb = ET.fromstring(z.read("xl/workbook.xml").decode())
    rels = ET.fromstring(z.read("xl/_rels/workbook.xml.rels").decode())
    rel_id_to_target: Dict[str, str] = {}
    rel_ns = "{http://schemas.openxmlformats.org/package/2006/relationships}"
    for rel in rels.findall(f"{rel_ns}Relationship"):
        rel_id_to_target[rel.get("Id")] = rel.get("Target")
    r_ns = "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}"
    for sh in wb.findall("a:sheets/a:sheet", _NS):
        if sh.get("name") == sheet_name:
            target = rel_id_to_target.get(sh.get(f"{r_ns}id"))
            if target is None:
                raise KeyError(f"no rels target for sheet {sheet_name!r}")
            return f"xl/{target}" if not target.startswith("xl/") else target
    raise KeyError(f"sheet {sheet_name!r} not found in workbook")


def read_field_descriptions(xlsx_path: Path) -> Dict[str, str]:
    """Return {FIELDNAME: DESCRIPTION} from the ACDOCA_Fields sheet."""
    with zipfile.ZipFile(xlsx_path) as z:
        strs = _shared_strings(z)
        sheet_xml = z.read(_find_sheet_path(z, "ACDOCA_Fields")).decode()
    sh = ET.fromstring(sheet_xml)
    rows = sh.findall(".//a:row", _NS)
    if not rows:
        return {}
    header = [_cell_value(c, strs) for c in rows[0].findall("a:c", _NS)]
    try:
        i_name = header.index("FIELDNAME")
        i_desc = header.index("DESCRIPTION")
    except ValueError as exc:
        raise RuntimeError(f"expected FIELDNAME and DESCRIPTION headers; got {header}") from exc

    out: Dict[str, str] = {}
    for r in rows[1:]:
        cells = r.findall("a:c", _NS)
        # Cells may be sparse — use the cell ref letter to map to column index.
        col_to_val: Dict[int, str] = {}
        for c in cells:
            ref = c.get("r") or ""
            letters = "".join(ch for ch in ref if ch.isalpha())
            if not letters:
                continue
            col = 0
            for ch in letters:
                col = col * 26 + (ord(ch) - ord("A") + 1)
            col -= 1
            col_to_val[col] = _cell_value(c, strs)
        name = col_to_val.get(i_name, "").strip()
        desc = col_to_val.get(i_desc, "").strip()
        if name:
            out[name] = desc
    return out


_HEADER = '''"""Auto-generated by scripts/build_field_descriptions.py — do not hand-edit.

Source: ACDOCA-table-structure.xlsx, sheet ACDOCA_Fields, column DESCRIPTION.
Maps SAP field technical name → short human-readable description, used by
``acdoca_generator.utils.schema.acdoca_schema`` to attach
``StructField.metadata["description"]`` so descriptions ride along to
BigQuery / Delta column comments at write time.
"""

from __future__ import annotations

FIELD_DESCRIPTIONS: dict[str, str] = {
'''


def _write_module(out_path: Path, mapping: Dict[str, str]) -> None:
    lines = [_HEADER]
    for name in sorted(mapping):
        desc = mapping[name].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{name}": "{desc}",\n')
    lines.append("}\n")
    out_path.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    if not _XLSX.exists():
        print(f"ERROR: {_XLSX} not found", file=sys.stderr)
        return 1
    mapping = read_field_descriptions(_XLSX)
    _write_module(_OUT, mapping)

    if str(_REPO) not in sys.path:
        sys.path.insert(0, str(_REPO))
    from acdoca_generator.config._field_specs_generated import FIELD_SPECS

    schema_names = {sap for sap, _sql, _t, _s in FIELD_SPECS}
    have = sum(1 for n in schema_names if mapping.get(n))
    missing = sorted(schema_names - {n for n in mapping if mapping[n]})
    print(f"Wrote {_OUT.relative_to(_REPO)} ({len(mapping)} entries from XLSX)")
    print(f"Schema coverage: {have} of {len(schema_names)} fields have descriptions")
    if missing:
        sample = ", ".join(missing[:10])
        more = f" (+{len(missing) - 10} more)" if len(missing) > 10 else ""
        print(f"Missing descriptions: {sample}{more}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
